name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/pngcheck ]

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  tag-repo:
    runs-on: ubuntu-latest
    needs: prepare
    if: startsWith(github.event.client_payload.ref, 'refs/tags/metanorma-v')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - run: |
          git config --global user.name "metanorma-ci"
          git config --global user.email "metanorma-ci@users.noreply.github.com"

      - run: echo pngcheck_VERSION=${pngcheck_TAG#*/metanorma-v} >> ${GITHUB_ENV}
        env:
          pngcheck_TAG: ${{ github.event.client_payload.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
          bundler-cache: true

      - run: |
          gem install gem-release
          gem bump --version ${pngcheck_VERSION} --no-commit

      - run: |
          sed -i -r 's/^(PNGCHECK_SHA =).*/\1 "${{ github.event.client_payload.sha256 }}"/' ext/layout.rb
          sed -i -r 's/^(PNGCHECK_VERSION =).*/\1 PngCheck::VERSION/' ext/layout.rb

      - name: Push commit and tag
        run: |
          git add ext/layout.rb *.gemspec
          git commit -m "Bump version to ${pngcheck_VERSION}"
          git tag v${pngcheck_VERSION}
          git push origin HEAD:${GITHUB_REF} --tags
